### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by shihw** [raulmt/homebridge-playbulb#1]
Are you ready to write this homebridge-plugin？

**Comment by raulmt** [comment]
well, yeah but, you know, it's not easy to make time for it. I've been mostly playing around with https://github.com/sandeepmistry/noble to control these bluetooth lights from Node, and also taking the chance to play around with RxJs… so it has been slow, I don't have much useful progress yet.

Why do you ask? Are you interested in using it? or developing it?

**Comment by raulmt** [comment]
FYI @shihw I decided to not implement this plugin. Yesterday my Mipow lights, both of them, just died when using them with "white" light. And only after less than 10 months with normal usage (a living room). So I don't have test devices and I will never have them again because I won't buy them again. I will stick with my other milight ones which, btw, have a nice homebridge plugin already.
